wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.12.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1635664038
    t:
      1:
      - 1
      - 3
      - 11
      - 12
      2:
      - 1
      - 3
      - 11
      - 12
      3:
      - 13
      - 16
      4: 3.8.5
      5: 0.12.6
      6: 4.12.2
      8:
      - 5
anneal_steps:
  desc: null
  value: 300000
bucket:
  desc: null
  value: bucket_for_tpu_gptj
ckpt_every:
  desc: null
  value: 500
comment:
  desc: null
  value: ''
cores_per_replica:
  desc: null
  value: 8
d_model:
  desc: null
  value: 4096
end_lr:
  desc: null
  value: 1.2e-05
eval_harness_tasks:
  desc: null
  value: []
gradient_accumulation_steps:
  desc: null
  value: 16
keep_every:
  desc: null
  value: 10000
layers:
  desc: null
  value: 28
lr:
  desc: null
  value: 0.00012
model_dir:
  desc: null
  value: tuned_to_finbase
n_heads:
  desc: null
  value: 16
n_vocab:
  desc: null
  value: 50400
name:
  desc: null
  value: tuned_to_base
norm:
  desc: null
  value: layernorm
optimizer:
  desc: null
  value:
  - optax._src.combine.chain.<locals>.init_fn
  - optax._src.combine.chain.<locals>.update_fn
pe:
  desc: null
  value: rotary
pe_rotary_dims:
  desc: null
  value: 64
per_replica_batch:
  desc: null
  value: 1
seq:
  desc: null
  value: 2048
total_steps:
  desc: null
  value: 350000
tpu_size:
  desc: null
  value: 256
train_set:
  desc: null
  value: fin.train.index
val_batches:
  desc: null
  value: 622
val_every:
  desc: null
  value: 500
val_set:
  desc: null
  value: {}
wandb_project:
  desc: null
  value: mesh-transformer-jax
warmup_steps:
  desc: null
  value: 3000
weight_decay:
  desc: null
  value: 0.1
